### ISSUE TITLE
an error in parseVars

### ISSUE THREAD

**Issue by timimin** [afonsonf/tlaplus-graph-explorer#2]
[trace3.zip](https://github.com/afonsonf/tlaplus-graph-explorer/files/6681801/trace3.zip)
Hello.
Seems that the parser can only work with model values. It doesn't properly handle values in quotes.

This trace produces an error when trying to use parseVars.

Alex.

**Comment by afonsonf** [comment]
Hi,
Sorry for the delayed response.
I pushed a new commit that should fix the parser. Does it solve the error you were facing?

**Comment by timimin** [comment]
Thanks a lot.
First of all i want to say your tool is of great use. Especially when multiple people involved in verification process.
First i thought i could fix the parser myself but certainly it would take too much time for me. So i found an easier way - preprocess trace string by removing all double quotes. It results in all string literals taking the look of model values. Such state modification is not critical for graphical representation.
Thanks. среда, 30 июня 2021г., 17:41 +03:00 от Afonso Fernandes  ***@***.*** :

**Comment by afonsonf** [comment]
I'm glad you found the tool useful!
If you find more errors or if you have any suggestion, please send them as it helps improve the tool.
