### ISSUE TITLE
string parsing error

### ISSUE THREAD

**Issue by timimin** [afonsonf/tlaplus-graph-explorer#3]
Hi.

Yet another issue. The parser cannot handle strings containing white spaces.

Thanks. Alex.

**Comment by afonsonf** [comment]
Hi, I added some tests in the expression parser (https://github.com/afonsonf/tlaplus-graph-explorer/tree/main/expr-parser), and I think white spaces are being properly parsed inside a string value. However empty string values were not being parsed and I added a fix in the last commit.

Can you give an example of the error you are encountering?
Maybe it can be how the strings are being escaped, not sure

**Comment by timimin** [comment]
Hi, this is my trace file. There is a state var named Trace where i store critical info for invariant violation error-trace visualization. This var represents a sequence of sequences:
`Trace = << <<allen, "p_change_status_load", "change_status_load">>,
   << allen,
      "p_change_status4",
      "update SUBMISSIONS set STATUS ~ stat where SUBMISSION_ID ~ s_id" >> >>`
The parser seems to stumble over the first white space.
[trace10.zip](https://github.com/afonsonf/tlaplus-graph-explorer/files/6980701/trace10.zip)
![error_screen](https://user-images.githubusercontent.com/82910332/129322157-7f8e55b6-1c8b-424e-981f-b3e97f800463.png)

**Comment by afonsonf** [comment]
Hi, I tried your trace, and I did not get any error.  I went over all the states in your trace file and all of them were parsed (I called the parseVars in the function drawState with stateStr to test it)
![image](https://user-images.githubusercontent.com/21228942/129327053-7d4e7724-f3b4-4371-b14d-f8929742b0c1.png)

Can you give more information with the state string that is triggering the error? Do you do alterations to the stateStr before calling parseVars?

**Comment by timimin** [comment]
Ooh...
Initially i stripped the stateStr string of the \" character due to the previous issue.
Now i've commented this line of code and it works well ).

`function drawNew2OldState(content, stateStr){
  let str = new String(stateStr);
  //str = str.replaceAll("\"", "");
  let vars = parseVars(str);`

Thanks and sorry.
