### ISSUE TITLE
Please clarify the instructions

### ISSUE THREAD

**Issue by homer-jay** [afonsonf/tlaplus-graph-explorer#4]
I'm trying to use your tool, which could be very useful, but after reading all the READMEs I have no clue what kind of file it expects. It says "big dot files", but **obtained from where**? All I have is a txt file that I obtained by clicking the 'export trace' button in the TLC error trace sidebar in the TLA+ Toolbox. This button exports a series of states to the clipboard. Is that the file this tool expects? I don't see any other way of exporting a trace.

**Please update the readme to show clearly how to obtain the input file.**

**Comment by afonsonf** [comment]
Hi, thanks for the feedback, added to the readme how to obtain the files that the application uses for the visualization
